quarkus:
  http:
    port: 8089

  log:
    console:
      format: "%d{HH:mm:ss} %-5p [%c{2.}] CorrelationId: %X{CorrelationId} (%t) %s%e%n"
    level: DEBUG

  rest-client:
    db-service.url: https://10.203.196.252/GIANOS3D/PORTALE2.gi
    cache-service.url: http://localhost:9000/orc/start